package br.com.sicva.model;
// Generated 01/04/2017 10:00:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aplica generated by hbm2java
 */
@Entity
@Table(name="aplica"
    ,catalog="sicva"
)
public class Aplica  implements java.io.Serializable {


     private Integer aplicaId;
     private Enfermeiro enfermeiro;
     private Vacinacao vacinacao;
     private String aplicaDosagem;
     private Date aplicaData;
     private String AplicaVacinaLote;

    public Aplica() {
    }

    public Aplica(Enfermeiro enfermeiro, String aplicaDosagem, Date aplicaData,Vacinacao vacinacao,String AplicaVacinaLote) {
       this.enfermeiro = enfermeiro;
       this.aplicaDosagem = aplicaDosagem;
       this.aplicaData = aplicaData;
       this.vacinacao = vacinacao;
       this.AplicaVacinaLote = AplicaVacinaLote;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="APLICA_ID", unique=true, nullable=false)
    public Integer getAplicaId() {
        return this.aplicaId;
    }
    
    public void setAplicaId(Integer aplicaId) {
        this.aplicaId = aplicaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APLICA_ENFERMEIRO_COREN", nullable=false)
    public Enfermeiro getEnfermeiro() {
        return this.enfermeiro;
    }
    
    public void setEnfermeiro(Enfermeiro enfermeiro) {
        this.enfermeiro = enfermeiro;
    }

    @ManyToOne
    @JoinColumn(name="APLICA_VACINACAO_ID", nullable=false)
    public Vacinacao getVacinacao() {
        return vacinacao;
    }

    public void setVacinacao(Vacinacao vacinacao) {
        this.vacinacao = vacinacao;
    }    
    
    @Column(name="APLICA_DOSAGEM", nullable=false, length=15)
    public String getAplicaDosagem() {
        return this.aplicaDosagem;
    }
    
    public void setAplicaDosagem(String aplicaDosagem) {
        this.aplicaDosagem = aplicaDosagem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APLICA_DATA", nullable=false, length=10)
    public Date getAplicaData() {
        return this.aplicaData;
    }
    
    public void setAplicaData(Date aplicaData) {
        this.aplicaData = aplicaData;
    }
    
    @Column(name="APLICA_VACINA_LOTE", nullable=false, length=15)
    public String getAplicaVacinaLote() {
        return AplicaVacinaLote;
    }

    public void setAplicaVacinaLote(String AplicaVacinaLote) {
        this.AplicaVacinaLote = AplicaVacinaLote;
    }

}


