package br.com.sicva.model;
// Generated 05/05/2017 18:52:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Atendente generated by hbm2java
 */
@Entity
@Table(name="atendente"
    ,catalog="sicva"
)
public class Atendente  implements java.io.Serializable {


     private Integer atendenteId;
     

    public Atendente() {
    }

    
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="ATENDENTE_ID", unique=true, nullable=false)
    public Integer getAtendenteId() {
        return this.atendenteId;
    }
    
    public void setAtendenteId(Integer atendenteId) {
        this.atendenteId = atendenteId;
    }


}


