package br.com.sicva.model;
// Generated 05/05/2017 18:52:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bairro generated by hbm2java
 */
@Entity
@Table(name="bairro"
    ,catalog="sicva"
)
public class Bairro  implements java.io.Serializable {


     private Integer bairroId;
     private Zona zona;
     private String bairroNome;
    

    public Bairro() {
    }

	
    public Bairro(Zona zona, String bairroNome) {
        this.zona = zona;
        this.bairroNome = bairroNome;
    }
    
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="BAIRRO_ID", unique=true, nullable=false)
    public Integer getBairroId() {
        return this.bairroId;
    }
    
    public void setBairroId(Integer bairroId) {
        this.bairroId = bairroId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BAIRRO_ZONA_ID", nullable=false)
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }

    
    @Column(name="BAIRRO_NOME", nullable=false, length=80)
    public String getBairroNome() {
        return this.bairroNome;
    }
    
    public void setBairroNome(String bairroNome) {
        this.bairroNome = bairroNome;
    }

}


