package br.com.sicva.model;
// Generated 01/04/2017 10:00:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,catalog="sicva"
)
public class Endereco  implements java.io.Serializable {


     private Integer endId;
     private Bairro bairro;
     private String endRua;
     private String endCep;
     private String endComplemento;

    public Endereco() {
    }

	
    public Endereco(Bairro bairro, String endRua, String endCep) {
        this.bairro = bairro;
        this.endRua = endRua;
        this.endCep = endCep;
    }
    public Endereco(Bairro bairro, String endRua, String endCep, String endComplemento) {
       this.bairro = bairro;
       this.endRua = endRua;
       this.endCep = endCep;
       this.endComplemento = endComplemento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="END_ID", unique=true, nullable=false)
    public Integer getEndId() {
        return this.endId;
    }
    
    public void setEndId(Integer endId) {
        this.endId = endId;
    }

@ManyToOne
    @JoinColumn(name="END_BAIRRO_ID", nullable=false)
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="END_RUA", nullable=false, length=80)
    public String getEndRua() {
        return this.endRua;
    }
    
    public void setEndRua(String endRua) {
        this.endRua = endRua;
    }

    
    @Column(name="END_CEP", nullable=false, length=9)
    public String getEndCep() {
        return this.endCep;
    }
    
    public void setEndCep(String endCep) {
        this.endCep = endCep;
    }

    
    @Column(name="END_COMPLEMENTO", length=50)
    public String getEndComplemento() {
        return this.endComplemento;
    }
    
    public void setEndComplemento(String endComplemento) {
        this.endComplemento = endComplemento;
    }




}


