package br.com.sicva.model;
// Generated 05/05/2017 18:52:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enfermeiro generated by hbm2java
 */
@Entity
@Table(name="enfermeiro"
    ,catalog="sicva"
)
public class Enfermeiro  implements java.io.Serializable {


    private String enfermeiroCoren;     

    public Enfermeiro() {
    }

	
    public Enfermeiro(String enfermeiroCoren) {
        this.enfermeiroCoren = enfermeiroCoren;
    }
    
   
    @Id    
    @Column(name="ENFERMEIRO_COREN", unique=true, nullable=false, length=10)
    public String getEnfermeiroCoren() {
        return this.enfermeiroCoren;
    }
    
    public void setEnfermeiroCoren(String enfermeiroCoren) {
        this.enfermeiroCoren = enfermeiroCoren;
    }


}


