package br.com.sicva.model;
// Generated 20/04/2017 18:08:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Enfermeiro generated by hbm2java
 */
@Entity
@Table(name="enfermeiro"
    ,catalog="sicva"
)
public class Enfermeiro  implements java.io.Serializable {


     private String enfermeiroCoren;
     private Usuario usuario;     

    public Enfermeiro() {
    }

	
    public Enfermeiro(String enfermeiroCoren, Usuario usuario) {
        this.enfermeiroCoren = enfermeiroCoren;
        this.usuario = usuario;
    }   
   
    @Id     
    @Column(name="ENFERMEIRO_COREN", unique=true, nullable=false, length=10)
    public String getEnfermeiroCoren() {
        return this.enfermeiroCoren;
    }
    
    public void setEnfermeiroCoren(String enfermeiroCoren) {
        this.enfermeiroCoren = enfermeiroCoren;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ENFERMEIRO_USUARIO_ID", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}


