package br.com.sicva.model;
// Generated 05/05/2017 18:52:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Fone generated by hbm2java
 */
@Entity
@Table(name="fone"
    ,catalog="sicva"
    , uniqueConstraints = {@UniqueConstraint(columnNames="FONE_NUMERO1"), @UniqueConstraint(columnNames="FONE_NUMERO2")} 
)
public class Fone  implements java.io.Serializable {


     private Integer foneId;
     private Paciente paciente;
     private String foneNumero1;
     private String foneNumero2;

    public Fone() {
    }

    public Fone(Paciente paciente, String foneNumero1, String foneNumero2) {
       this.paciente = paciente;
       this.foneNumero1 = foneNumero1;
       this.foneNumero2 = foneNumero2;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="FONE_ID", unique=true, nullable=false)
    public Integer getFoneId() {
        return this.foneId;
    }
    
    public void setFoneId(Integer foneId) {
        this.foneId = foneId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FONE_PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="FONE_NUMERO1", unique=true, nullable=false, length=15)
    public String getFoneNumero1() {
        return this.foneNumero1;
    }
    
    public void setFoneNumero1(String foneNumero1) {
        this.foneNumero1 = foneNumero1;
    }

    
    @Column(name="FONE_NUMERO2", unique=true, nullable=false, length=15)
    public String getFoneNumero2() {
        return this.foneNumero2;
    }
    
    public void setFoneNumero2(String foneNumero2) {
        this.foneNumero2 = foneNumero2;
    }




}


