package br.com.sicva.model;
// Generated 01/04/2017 10:00:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ubs generated by hbm2java
 */
@Entity
@Table(name="ubs"
    ,catalog="sicva"
    , uniqueConstraints = {@UniqueConstraint(columnNames="UBS_NOME"), @UniqueConstraint(columnNames="UBS_FONE")} 
)
public class Ubs  implements java.io.Serializable {


     private Integer ubsId;
     private Bairro bairro;
     private String ubsNome;
     private String ubsFone;
     

    public Ubs() {
    }

	
    public Ubs(Bairro bairro, String ubsNome, String ubsFone) {
        this.bairro = bairro;
        this.ubsNome = ubsNome;
        this.ubsFone = ubsFone;
    }
    
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="UBS_ID", unique=true, nullable=false)
    public Integer getUbsId() {
        return this.ubsId;
    }
    
    public void setUbsId(Integer ubsId) {
        this.ubsId = ubsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UBS_BAIRRO_ID", nullable=false)
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="UBS_NOME", unique=true, nullable=false, length=80)
    public String getUbsNome() {
        return this.ubsNome;
    }
    
    public void setUbsNome(String ubsNome) {
        this.ubsNome = ubsNome;
    }

    
    @Column(name="UBS_FONE", unique=true, nullable=false, length=15)
    public String getUbsFone() {
        return this.ubsFone;
    }
    
    public void setUbsFone(String ubsFone) {
        this.ubsFone = ubsFone;
    }


}


