package br.com.sicva.model;
// Generated 20/04/2017 18:08:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="sicva"
    , uniqueConstraints = @UniqueConstraint(columnNames="USUARIO_CPF") 
)
public class Usuario  implements java.io.Serializable {


     private Integer usuarioId;
     private String usuarioCpf;
     private String usuarioNome;
     private String usuarioSenha;
     

    public Usuario() {
    }

	
    public Usuario(String usuarioCpf, String usuarioNome, String usuarioSenha) {
        this.usuarioCpf = usuarioCpf;
        this.usuarioNome = usuarioNome;
        this.usuarioSenha = usuarioSenha;
    }
    
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="USUARIO_ID", unique=true, nullable=false)
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    
    @Column(name="USUARIO_CPF", unique=true, nullable=false, length=14)
    public String getUsuarioCpf() {
        return this.usuarioCpf;
    }
    
    public void setUsuarioCpf(String usuarioCpf) {
        this.usuarioCpf = usuarioCpf;
    }

    
    @Column(name="USUARIO_NOME", nullable=false, length=80)
    public String getUsuarioNome() {
        return this.usuarioNome;
    }
    
    public void setUsuarioNome(String usuarioNome) {
        this.usuarioNome = usuarioNome;
    }

    
    @Column(name="USUARIO_SENHA", nullable=false, length=60)
    public String getUsuarioSenha() {
        return this.usuarioSenha;
    }
    
    public void setUsuarioSenha(String usuarioSenha) {
        this.usuarioSenha = usuarioSenha;
    }

}


