package br.com.sicva.model;
// Generated 05/05/2017 18:52:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="sicva"
    , uniqueConstraints = @UniqueConstraint(columnNames="USUARIO_CPF") 
)
public class Usuario  implements java.io.Serializable {


     private Integer usuarioId;
     private Atendente atendente;
     private Enfermeiro enfermeiro;
     private String usuarioCpf;
     private String usuarioNome;
     private String usuarioSenha;
     private String usuarioStatus;

    public Usuario() {
    }

	
    public Usuario(String usuarioCpf, String usuarioNome, String usuarioSenha, String usuarioStatus) {
        this.usuarioCpf = usuarioCpf;
        this.usuarioNome = usuarioNome;
        this.usuarioSenha = usuarioSenha;
        this.usuarioStatus = usuarioStatus;
    }
    public Usuario(Atendente atendente, Enfermeiro enfermeiro, String usuarioCpf, String usuarioNome, String usuarioSenha, String usuarioStatus) {
       this.atendente = atendente;
       this.enfermeiro = enfermeiro;
       this.usuarioCpf = usuarioCpf;
       this.usuarioNome = usuarioNome;
       this.usuarioSenha = usuarioSenha;
       this.usuarioStatus = usuarioStatus;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="USUARIO_ID", unique=true, nullable=false)
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_ATENDENTE")
    public Atendente getAtendente() {
        return this.atendente;
    }
    
    public void setAtendente(Atendente atendente) {
        this.atendente = atendente;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_ENFERMEIRO")
    public Enfermeiro getEnfermeiro() {
        return this.enfermeiro;
    }
    
    public void setEnfermeiro(Enfermeiro enfermeiro) {
        this.enfermeiro = enfermeiro;
    }

    
    @Column(name="USUARIO_CPF", unique=true, nullable=false, length=14)
    public String getUsuarioCpf() {
        return this.usuarioCpf;
    }
    
    public void setUsuarioCpf(String usuarioCpf) {
        this.usuarioCpf = usuarioCpf;
    }

    
    @Column(name="USUARIO_NOME", nullable=false, length=80)
    public String getUsuarioNome() {
        return this.usuarioNome;
    }
    
    public void setUsuarioNome(String usuarioNome) {
        this.usuarioNome = usuarioNome;
    }

    
    @Column(name="USUARIO_SENHA", nullable=false, length=60)
    public String getUsuarioSenha() {
        return this.usuarioSenha;
    }
    
    public void setUsuarioSenha(String usuarioSenha) {
        this.usuarioSenha = usuarioSenha;
    }

    
    @Column(name="USUARIO_STATUS", nullable=false, length=10)
    public String getUsuarioStatus() {
        return this.usuarioStatus;
    }
    
    public void setUsuarioStatus(String usuarioStatus) {
        this.usuarioStatus = usuarioStatus;
    }




}


