package br.com.sicva.model;
// Generated 20/04/2017 18:08:46 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacinacao generated by hbm2java
 */
@Entity
@Table(name="vacinacao"
    ,catalog="sicva"
)
public class Vacinacao  implements java.io.Serializable {


     private Integer vacinacaoId;
     private Enfermeiro enfermeiro;
     private Paciente paciente;
     private Ubs ubs;
     private Vacina vacina;
     private Date vacinacaoProxDt;
     private String vacinacaoStatus;
     private String vacinacaoLoteVaci;
     private String vacinacaoDosagem;
     private Date vacinacaoDtPrevista;

    public Vacinacao() {
    }

	
    public Vacinacao(Paciente paciente, Vacina vacina, String vacinacaoStatus, Date vacinacaoDtPrevista) {
        this.paciente = paciente;
        this.vacina = vacina;
        this.vacinacaoStatus = vacinacaoStatus;
        this.vacinacaoDtPrevista = vacinacaoDtPrevista;
    }
    public Vacinacao(Enfermeiro enfermeiro, Paciente paciente, Ubs ubs, Vacina vacina, Date vacinacaoProxDt, String vacinacaoStatus, String vacinacaoLoteVaci, String vacinacaoDosagem, Date vacinacaoDtPrevista) {
       this.enfermeiro = enfermeiro;
       this.paciente = paciente;
       this.ubs = ubs;
       this.vacina = vacina;
       this.vacinacaoProxDt = vacinacaoProxDt;
       this.vacinacaoStatus = vacinacaoStatus;
       this.vacinacaoLoteVaci = vacinacaoLoteVaci;
       this.vacinacaoDosagem = vacinacaoDosagem;
       this.vacinacaoDtPrevista = vacinacaoDtPrevista;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VACINACAO_ID", unique=true, nullable=false)
    public Integer getVacinacaoId() {
        return this.vacinacaoId;
    }
    
    public void setVacinacaoId(Integer vacinacaoId) {
        this.vacinacaoId = vacinacaoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_ENFERM_COREN")
    public Enfermeiro getEnfermeiro() {
        return this.enfermeiro;
    }
    
    public void setEnfermeiro(Enfermeiro enfermeiro) {
        this.enfermeiro = enfermeiro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_UBS_ID")
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_VACINA_ID", nullable=false)
    public Vacina getVacina() {
        return this.vacina;
    }
    
    public void setVacina(Vacina vacina) {
        this.vacina = vacina;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VACINACAO_DT_APLIC", length=10)
    public Date getVacinacaoDtAplic() {
        return this.vacinacaoProxDt;
    }
    
    public void setVacinacaoDtAplic(Date vacinacaoProxDt) {
        this.vacinacaoProxDt = vacinacaoProxDt;
    }

    
    @Column(name="VACINACAO_STATUS", nullable=false, length=15)
    public String getVacinacaoStatus() {
        return this.vacinacaoStatus;
    }
    
    public void setVacinacaoStatus(String vacinacaoStatus) {
        this.vacinacaoStatus = vacinacaoStatus;
    }

    
    @Column(name="VACINACAO_LOTE_VACI", length=10)
    public String getVacinacaoLoteVaci() {
        return this.vacinacaoLoteVaci;
    }
    
    public void setVacinacaoLoteVaci(String vacinacaoLoteVaci) {
        this.vacinacaoLoteVaci = vacinacaoLoteVaci;
    }

    
    @Column(name="VACINACAO_DOSAGEM", length=15)
    public String getVacinacaoDosagem() {
        return this.vacinacaoDosagem;
    }
    
    public void setVacinacaoDosagem(String vacinacaoDosagem) {
        this.vacinacaoDosagem = vacinacaoDosagem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VACINACAO_DT_PREVISTA", nullable=false, length=10)
    public Date getVacinacaoDtPrevista() {
        return this.vacinacaoDtPrevista;
    }
    
    public void setVacinacaoDtPrevista(Date vacinacaoDtPrevista) {
        this.vacinacaoDtPrevista = vacinacaoDtPrevista;
    }




}


