package br.com.sicva.model;
// Generated 01/04/2017 10:00:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vacina generated by hbm2java
 */
@Entity
@Table(name="vacina"
    ,catalog="sicva"
)
public class Vacina  implements java.io.Serializable {


     private Integer vacinaId;
     private String vacinaLote;
     private String vacinaNome;
    

    public Vacina() {
    }

	
    public Vacina(String vacinaLote, String vacinaNome) {
        this.vacinaLote = vacinaLote;
        this.vacinaNome = vacinaNome;
    }
   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VACINA_ID", unique=true, nullable=false)
    public Integer getVacinaId() {
        return this.vacinaId;
    }
    
    public void setVacinaId(Integer vacinaId) {
        this.vacinaId = vacinaId;
    }

    
    @Column(name="VACINA_LOTE", nullable=false, length=30)
    public String getVacinaLote() {
        return this.vacinaLote;
    }
    
    public void setVacinaLote(String vacinaLote) {
        this.vacinaLote = vacinaLote;
    }

    
    @Column(name="VACINA_NOME", nullable=false, length=50)
    public String getVacinaNome() {
        return this.vacinaNome;
    }
    
    public void setVacinaNome(String vacinaNome) {
        this.vacinaNome = vacinaNome;
    }




}


