package br.com.sicva.model;
// Generated 01/04/2017 10:00:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacinacao generated by hbm2java
 */
@Entity
@Table(name="vacinacao"
    ,catalog="sicva"
)
public class Vacinacao  implements java.io.Serializable {


     private Integer vacinacaoId;
     private Paciente paciente;
     private Ubs ubs;
     private Vacina vacina;
     private Date vacinacaoProxDt;
     private String vacinacaoStatus;
     private String vacinacaoFaixaEteria;

    public Vacinacao() {
    }

    public Vacinacao(Paciente paciente, Ubs ubs, Vacina vacina, Date vacinacaoProxDt, String vacinacaoStatus, String vacinacaoFaixaEteria) {
       this.paciente = paciente;
       this.ubs = ubs;
       this.vacina = vacina;
       this.vacinacaoProxDt = vacinacaoProxDt;
       this.vacinacaoStatus = vacinacaoStatus;
       this.vacinacaoFaixaEteria = vacinacaoFaixaEteria;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VACINACAO_ID", unique=true, nullable=false)
    public Integer getVacinacaoId() {
        return this.vacinacaoId;
    }
    
    public void setVacinacaoId(Integer vacinacaoId) {
        this.vacinacaoId = vacinacaoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_UBS_ID", nullable=false)
    public Ubs getUbs() {
        return this.ubs;
    }
    
    public void setUbs(Ubs ubs) {
        this.ubs = ubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACINACAO_VACINA_ID", nullable=false)
    public Vacina getVacina() {
        return this.vacina;
    }
    
    public void setVacina(Vacina vacina) {
        this.vacina = vacina;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VACINACAO_PROX_DT", nullable=false, length=10)
    public Date getVacinacaoProxDt() {
        return this.vacinacaoProxDt;
    }
    
    public void setVacinacaoProxDt(Date vacinacaoProxDt) {
        this.vacinacaoProxDt = vacinacaoProxDt;
    }

    
    @Column(name="VACINACAO_STATUS", nullable=false, length=15)
    public String getVacinacaoStatus() {
        return this.vacinacaoStatus;
    }
    
    public void setVacinacaoStatus(String vacinacaoStatus) {
        this.vacinacaoStatus = vacinacaoStatus;
    }

    
    @Column(name="VACINACAO_FAIXA_ETERIA", nullable=false, length=10)
    public String getVacinacaoFaixaEteria() {
        return this.vacinacaoFaixaEteria;
    }
    
    public void setVacinacaoFaixaEteria(String vacinacaoFaixaEteria) {
        this.vacinacaoFaixaEteria = vacinacaoFaixaEteria;
    }




}


