package br.com.sicva.model;
// Generated 05/05/2017 18:52:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vacina generated by hbm2java
 */
@Entity
@Table(name="vacina"
    ,catalog="sicva"
)
public class Vacina  implements java.io.Serializable {


     private Integer vacinaId;
     private String vacinaNome;
     private int vacinaqdtedose;
     

    public Vacina() {
    }

	
    public Vacina(String vacinaNome, int vacinaqdtedose) {
        this.vacinaNome = vacinaNome;
        this.vacinaqdtedose = vacinaqdtedose;
    }
   
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="VACINA_ID", unique=true, nullable=false)
    public Integer getVacinaId() {
        return this.vacinaId;
    }
    
    public void setVacinaId(Integer vacinaId) {
        this.vacinaId = vacinaId;
    }

    
    @Column(name="VACINA_NOME", nullable=false, length=50)
    public String getVacinaNome() {
        return this.vacinaNome;
    }
    
    public void setVacinaNome(String vacinaNome) {
        this.vacinaNome = vacinaNome;
    }

    
    @Column(name="VACINAQDTEDOSE", nullable=false)
    public int getVacinaqdtedose() {
        return this.vacinaqdtedose;
    }
    
    public void setVacinaqdtedose(int vacinaqdtedose) {
        this.vacinaqdtedose = vacinaqdtedose;
    }


}


