package br.com.sicva.model;
// Generated 01/04/2017 10:00:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,catalog="sicva"
)
public class Zona  implements java.io.Serializable {


     private Integer zonaId;
     private String zonaNome;

    public Zona() {
    }

    public Zona(String zonaNome) {
       this.zonaNome = zonaNome;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ZONA_ID", unique=true, nullable=false)
    public Integer getZonaId() {
        return this.zonaId;
    }
    
    public void setZonaId(Integer zonaId) {
        this.zonaId = zonaId;
    }

    
    @Column(name="ZONA_NOME", nullable=false, length=80)
    public String getZonaNome() {
        return this.zonaNome;
    }
    
    public void setZonaNome(String zonaNome) {
        this.zonaNome = zonaNome;
    }




}


